name: aldjazair
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  provider: ^5.0.0
  email_validator: ^2.0.1
  change_app_package_name: ^1.0.0
  flutter_spinkit: "^4.1.2"
  flutter_map: ^0.12.0
  cloud_firestore: "^2.0.0"
  flutter_map_marker_popup: ^0.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  latlong2: ^0.8.0
  carousel_slider: ^3.0.0
  flutter_map_location: ^0.10.0
  flutter_map_location_marker: ^0.0.8
  flutter_map_tappable_polyline: ^1.3.1
  http: ^0.13.3
  location: ^4.2.3
  timer_builder: ^2.0.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.1+3
  image_picker_for_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/emir.png
    - assets/logo.png
    - assets/test.jpg
    - assets/test.png
    - assets/Images/
    - assets/user.jpg
    - assets/user2.jpg
  fonts:
    - family: Patrick
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
        - style: normal
     
